### ISSUE TITLE
Pure authentication blanks out customer names

### ISSUE THREAD

**Issue by nbuckel** [Parature/Passthrough2.0#3]
If you use the example JSON in the documentation to perform a pure authentication to get a refID then the customer's first and last names get blanked out, you have to add in the cFname and cLname to stop it from happening.

for reference, here's the section:

"Another sample JSON with necessary user identifier information to perform pure authentication alone

{
  "subject": "yourSecurePassthroughInstanceID",
  "payload": {
    "sessEmail": "activeCSREmailID@abc.com",
    "cEmail": "parature_tester@parature.com",
    "cUname": "userName",
    "deptID": "45014",
      }
}"

**Comment by shivakav** [comment]
Hello Nathan, you are right. It expects first name and last name to be sent, when passthrough is enabled to update records. Otherwise you could skip the first name and last name. I have updated the Document to reflect that earlier. Cheers!

**Comment by nbuckel** [comment]
HI Shiva,

Does that mean passthrough can be set to not update records? Do I need to log a ticket to get that changed?

Thanks,

Nick

**Comment by shivakav** [comment]
Yes, based on your use case if you don’t use Passthrough to update records. You can raise a parature support ticket to turn off update of records during Passthrough Nick.

Cheers
Shiva
